apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: preu-topeducation-frontend
          image: aaldeao/preu-topeducation-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer