apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  #base de dato Cuota
  POSTGRES_DB_CUOTA: preu_topeducationcuota
  #base de dato Estudiante
  POSTGRES_DB_ESTUDIANTE: preu_topeducationestudiante
  #base de dato Prueba
  POSTGRES_DB_PRUEBA: preu_topeducationprueba